server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;
    location = /runtime-config.json { add_header Cache-Control "no-store"; try_files $uri =404; }
    location / { try_files $uri $uri/ /index.html; }
}
